#All configuration options can be found in config.py
mqtt:
  host: 10.0.0.160
  port: 1883
  user: hass
  password: hass
  topic_prefix: amblegpt

frigate:
  host: 10.0.0.160
  port: 5000
  update_label: False
  update_description: True


image:
  interval: 4
  frame_size: 512
  max_frames: 5
  min_frames: 3
  image_quality: low

event:
  clips: False
  snapshots: True
  debounce: 10
  process_complete: False
  pre_wait_time: 4

cameras:
  test:
    enabled: True
    prompt: >-
      This footage is from a camera located inside of a home office, facing the only door.
      Sometimes one or two people enter and leave the office, this is not unusual.
  front-door:
    enabled: True
    prompt: >-
      The camera that took the footage is a doorbell camera outside the front door of the house.
      The door is on the left side of the video frame and the exit is on the right side.
  outside:
    enabled: True
    prompt: >-
      The camera that took the footage is mounted on the frame of the front window of the house facing the street.
      The street allow guest parking and it is normal to see cars parked on the street.
      There might also be people walking (with their dogs) on the sidewalk before 9pm.

prompt: >-
  If necessary, uncomment this and use your prompt here
  The default prompt can be found in prompt.py